name: neural-spd-inversion
channels:
    - conda-forge
    - defaults
dependencies:
    - python
    - pooch
    - numpy
    - pysheds
    - pytorch
    - pandas
    - matplotlib
    - pip
    - pip:
      - -e .

      - -e ./lib/landlab_torch_tools
