#+title: Length Scales
#+PROPERTY: header-args:python :python /home/jo/cub/research/projects/neural-spd-inversion-proj/neural-spd-inversion/.venv/bin/python :session length-scales


* Motivation
There is a kink in the results of the valley spacing and drainage density experiments.  Jean suggested that it could be due to the D/K value at that point corresponding to a characterstic scale that matched up with my model domain or resolution.  They are at different locations for each experiment, so the corresponding critical length should be calculated for a range of \(D/K\) values.


* Equation
Using the formulation from Theodoratos et al. 2018 ([cite:@theodoratosScalingSimilarityStreampower2018]) we have the following equation
\(l_c=\left(K^{-1}D^nU^{1-n}\right)^{1/(n+2m)\)
In our experiments we used an \(m=0.3\) and \(n=0.7\) which means we can not simply substitute \(D/K\), which our network infers, into the equation.  Instead we write the equation in terms of \(K\) and solve it for a range of \(K\) values.  Let \(r=D/K\).  Then \(D=rK\) and
\(l_c=\left(K^{-1}(rK)^nU^{1-n}\right)^{1/(n+2m)\)

\(l_c=\left(K^{n-1}r^nU^{1-n}\right)^{1/(n+2m)\)

\(l_c=\left(^{}K^{-0.3}r^{0.7}U^{}^{0.3}\right)^{1/(1.3)\)
In our models \(U=1e^{-4}m\) and \(1.5e^{-4}<K<2e^{-3}\).
The \(r\) values we would like to investigate are when \(log_{10}(D/K)=-2.5\) for the drainage density experiment and when \(-11<\log_{10}(D/K)<-7.5\) for the valley spacing experiment.

* Code
#+begin_src python
import numpy as np
import matplotlib.pyplot as plt

def lc(K,r,U=1e-4,m=0.3,n=0.7):
    return ((K**(n-1))*(r**n)*(U**(1-n)))**(1/(n+2*m))

r_dd = 10**(-2.5)
r_vs_min = 10**(-11)
r_vs_max = 10**(-7.5)
K_min = 1.5e-4
K_max = 2e-3
r_vs = np.linspace(r_vs_min, r_vs_max, 100)
K = np.linspace(K_min, K_max, 100)
width = 500
height = 1500
resolution = 5

lc_dd = lc(K, r_dd)
lc_vs_min = lc(K, r_vs_min)
lc_vs_max = lc(K, r_vs_max)
fig, axs = plt.subplots(2)
axs[0].plot(K, lc_dd)
#axs[0].hlines([width,height, resolution], K.min(), K.max())
axs[1].plot(K, lc_vs_min, label="Low VS")
axs[1].plot(K, lc_vs_max, label="High VS")
#axs[1].hlines([width,height, resolution],K.min(),K.max())
fig.show()
#+end_src
The kink does not match a length scale at all related to my model domain or resolution.
#+RESULTS:
: None
